### ISSUE TITLE
Language statistics for gitlab

### ISSUE THREAD

**Issue by koffeinfrei** [panter/dashboard.panter.ch#20]
Language statistics are missing from gitlab.

Possible solution
- Use the existing repo folders on git.panter.ch
- Use https://github.com/github/linguist to detect the languages
- Expose some mini-API for consumption from dashboard.panter.ch

**Comment by toupeira** [comment]
There's also a half-finished PR at https://github.com/gitlabhq/gitlabhq/pull/6946

**Comment by koffeinfrei** [comment]
Use linguist directly, also for github, as we have all the repos cloned on the server anyway (because of technologist)
