### ISSUE TITLE
Dashboard is not responsive

### ISSUE THREAD

**Issue by domicode** [panter/dashboard.panter.ch#3]
you can drag and drop the element but they don't rearrange automatically if you have a smaller window size.

**Comment by koffeinfrei** [comment]
Dashing is actually not meant to be responsive, it's purpose is to be shown on big screens.
Not sure how we should go about this...

**Comment by domicode** [comment]
Probably we can use a different grid layout - maybe only 1 x X wide so on the phone it would look nicer and then trigger the grid according which browser you are using. I will try if something like this could work and look good. So kind of semi responsive.

**Comment by koffeinfrei** [comment]
Ok. IMO you could also try to get rid of the drag n drop functionality. I doesn't server any purpose but to confuse the user.
