### ISSUE TITLE
Drag n drop bug with small screensize

### ISSUE THREAD

**Issue by hexagon6** [panter/dashboard.panter.ch#43]
drag n drop is buggy once you move an element with a smaller screensize below a certain y position.

The element moves only down after that position while dragging in any direction.

**Comment by koffeinfrei** [comment]
Thanks for your report.

This is a problem of http://dashing.io. You could consider posting your issue there (presumably on the forked project, the original one is inactive).

We'll redesign the dashboard anyway and will not be using dashing anymore for the new version.
